
#ifndef ELEV_PORT
#define ELEV_PORT

#define INIT_COMMAND = 1
#define MOTOR_DIRECTION_COMMAND = 2
#define BUTTON_LAMP_COMMAND = 3
#define FLOOR_INDICATOR_COMMAND = 4
#define DOOR_OPEN_COMMAND = 5
#define BUTTON_SIGNAL_COMMAND = 6
#define FLOOR_SENSOR_SIGNAL_COMMAND = 7

#endif